### ISSUE TITLE
Logistic Regression Error: 'logpol.tba does not exist'

### ISSUE THREAD

**Issue by JacobUSGS** [gtkfi/ArcSDM#107]
Hello,

I get an error when trying to run the Logistic Regression tool: 'logpol.tba does not exist'.

The data I'm trying to use work in a Weights of Evidence (Calculate Response) tool.

Please let me know if I can provide more information.

Thanks,

Jacob

**Comment by trotor** [comment]
Just straight out of memory: I think it should be logpol.bat   - are you
sure it is looking for tba?

**Comment by JacobUSGS** [comment]
Yes, I copied & pasted the error message. 

I looked for a file with the name 'logpol' (using any file type extension) and I did not find it in the folder the Logistic Regression tool was looking for it in. Thanks for your response.

**Comment by JacobUSGS** [comment]
I tried the same process on a different computer and got a different result. It may be safe to say that the issue of looking for 'logpol.tba' may be specific to my first computer. I ran into a new problem on the second computer:

The Logistic Regression tool ran to completion, but the output post probability raster 'LR_pprb" equaled '0' across my study area. This appears to be an error.

I noticed that the output polynomial table 'LR_logpol.dbf' contained coefficients that looks like they were calculated correctly. 

I also noticed that a raster named 'tmp_ucras' had the same number of intervals as the output polynomial table and seems to be directly associated. Can I join values from the output polynomial to the 'tmp_ucras' raster to display post probability & standard deviation?

Please let me know if I can provide additional information. Thanks,

**Comment by trotor** [comment]
Hi, very good to hear you got pat that first problem - it still sounds like
some virusscanner or company policy or such protecting computer from
runnable batch scripts by renaming .bat to .tba.

On your another question: tmp_ucras seems to be used in various places in
the code - so depending on where it failed it could be correct. Did you get
new error messages? Are you getting these errors with demo dataset also?

**Comment by trotor** [comment]
#103 fixes merged - please try if it fixes some of these problems too

**Comment by Eliasmgprado** [comment]
> Hello,
> 
> I get an error when trying to run the Logistic Regression tool: 'logpol.tba does not exist'.
> 
> The data I'm trying to use work in a Weights of Evidence (Calculate Response) tool.
> 
> Please let me know if I can provide more information.
> 
> Thanks,
> 
> Jacob

I had the same error ('logpol.tba does not exist').

By checking the logisticregression.py file, I noticed that the error is related to running sdmlr.exe. Running this executable at the command prompt provides the following error:

The value of the STATUS specifier in an OPEN statement does not match the status of the file.

This error is a fortran95 error related to the absence of some files in the path that the executable was run.

So finally, I can correct this error by changing the scratch environment to the same as the workspace enviroment. In this way, the param.dat and case.dat files created in the logistregression.py run are placed in the same folder as the .dbf weights tables and the raster evidence layers.

Hope this can help.

Best Regards,

Elias Prado
Brazil Geological Survey

**Comment by artolaiho** [comment]
Presumably, this problem has been resolved because the questioner has not continued the discussion. Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.

**Comment by Tayyibriaz** [comment]
hello, 
The problem is still there in the updated versions of ArcSDM too. I have noticed that with more than 5 rasters we faced same problem but less than 5 it is working.


Executing: LogisticRegressionTool road;slope;stream;fault;geo;rain;pga f;f;f;f;f;f;f F:\LR_N\weight\road.dbf;F:\LR_N\weight\slope.dbf;F:\LR_N\weight\stream.dbf;F:\LR_N\weight\fault_CT.dbf;F:\LR_N\weight\geo_CT.dbf;F:\LR_N\weight\rain_CT.dbf;F:\LR_N\weight\pga_CT.dbf trainig -99 1 F:\LR_N\new\LR_logpol F:\LR_N\new\LR_coeff5 F:\LR_N\new\LR_pprb5 F:\LR_N\new\LR_std5 F:\LR_N\new\LR_conf5
Start Time: Sun Feb 14 10:25:51 2021
Running script LogisticRegressionTool...
Checking environment...
Input rasters: [u'road', u'slope', u'stream', u'fault', u'geo', u'rain', u'pga']
Evidence_types: [u'f', u'f', u'f', u'f', u'f', u'f', u'f']
Wts_Tables: [u'F:\\LR_N\\weight\\road.dbf', u'F:\\LR_N\\weight\\slope.dbf', u'F:\\LR_N\\weight\\stream.dbf', u'F:\\LR_N\\weight\\fault_CT.dbf', u'F:\\LR_N\\weight\\geo_CT.dbf', u'F:\\LR_N\\weight\\rain_CT.dbf', u'F:\\LR_N\\weight\\pga_CT.dbf']
F:\LR_N\weight\road.dbf
F:\LR_N\weight\slope.dbf
F:\LR_N\weight\stream.dbf
F:\LR_N\weight\fault_CT.dbf
F:\LR_N\weight\geo_CT.dbf
F:\LR_N\weight\rain_CT.dbf
F:\LR_N\weight\pga_CT.dbf
TrainPts: trainig
MissingDataValue: -99

========== arcsdm values  ==========
                     ArcSDM 5.03-1 for ArcGis (Pro and Desktop)

Arcgis environment:  Desktop (10.4.1)
Workspace:           F:\LR_N\new (FileSystem)
Scratch workspace:   F:\LR_N\new (FileSystem)
Map Units:           meter
Mask:                "study.shp" and it is FeatureLayer
Warning: You should only use single value raster type masks!
Mask size:           3112.83127151
Cell Size:           30
# Training Sites:    1670
Unit Cell Area:      1.0km^2, Cells in area: 3112.83127151 
Prior Probability:   0.536489
Training Set:        F:\LR_N\trainig.shp
Study Area Raster:   F:\LR_N\study.shp
Study Area Area:     3112.83127151km^2
Creating Generalized Class rasters.
Input_Raster:        road
Output_Raster:       F:\LR_N\new\road_G0
Temp_Raster:         F:\LR_N\new\tmp_rst26 (6)
Output_Raster:       F:\LR_N\new\Lookup_tmp_27 (6)
Input_Raster:        slope
Output_Raster:       F:\LR_N\new\slope_G0
Temp_Raster:         F:\LR_N\new\tmp_rst27 (8)
Output_Raster:       F:\LR_N\new\Lookup_tmp_28 (7)
Input_Raster:        stream
Output_Raster:       F:\LR_N\new\stream_G0
Temp_Raster:         F:\LR_N\new\tmp_rst28 (6)
Output_Raster:       F:\LR_N\new\Lookup_tmp_29 (5)
Input_Raster:        fault
Output_Raster:       F:\LR_N\new\fault_G0
Temp_Raster:         F:\LR_N\new\tmp_rst29 (6)
Output_Raster:       F:\LR_N\new\Lookup_tmp_30 (4)
Input_Raster:        geo
Output_Raster:       F:\LR_N\new\geo_G0
Temp_Raster:         F:\LR_N\new\tmp_rst30 (15)
Output_Raster:       F:\LR_N\new\Lookup_tmp_31 (8)
Input_Raster:        rain
Output_Raster:       F:\LR_N\new\rain_G0
Temp_Raster:         F:\LR_N\new\tmp_rst31 (7)
Output_Raster:       F:\LR_N\new\Lookup_tmp_32 (5)
Input_Raster:        pga
Output_Raster:       F:\LR_N\new\pga_G0
Temp_Raster:         F:\LR_N\new\tmp_rst32 (7)
Output_Raster:       F:\LR_N\new\Lookup_tmp_33 (7)
Combining...F:\LR_N\new\Lookup_tmp_27;F:\LR_N\new\Lookup_tmp_28;F:\LR_N\new\Lookup_tmp_29;F:\LR_N\new\Lookup_tmp_30;F:\LR_N\new\Lookup_tmp_31;F:\LR_N\new\Lookup_tmp_32;F:\LR_N\new\Lookup_tmp_33
Combine done succesfully.
Writing Logistic Regression input files...
Write a parameter file to the ArcView extension directory
Running F:\LR_N\new\scratch\sdmlr.bat: 
Logistic regression output file F:\LR_N\new\scratch\logpol.tba does not exist.
 Error in case.dat or param.dat. 
GP ERRORS:


PYTHON ERRORS:
Traceback Info:
  File "F:\LR_N\ArcSDM-master\Toolbox\arcsdm\logisticregression.py", line 481, in Execute
    raise Exception

Error Info:
    <type 'exceptions.Exception'>: 


Traceback (most recent call last):
  File "<string>", line 1576, in execute
  File "F:\LR_N\ArcSDM-master\Toolbox\arcsdm\logisticregression.py", line 481, in Execute
    raise Exception
Exception

Failed to execute (LogisticRegressionTool).
Failed at Sun Feb 14 10:28:21 2021 (Elapsed Time: 2 minutes 29 seconds)


is there any solution?
